
import {
  Home,
  HeartPulse,
  LineChart,
  Scaling,
  Baby,
  Weight,
  PersonStanding,
  BrainCircuit,
  Armchair,
  Ruler,
  Bone,
  History
} from 'lucide-react';
import type { Tool } from './types';

export const TOOLS: Tool[] = [
  {
    id: 'home',
    name: 'home_dashboard_name',
    description: 'home_dashboard_description',
    path: '/home/',
    Icon: Home,
    gradient: 'from-blue-500 to-cyan-400',
  },
  {
    id: 'blood-pressure',
    name: 'bp_analyzer_name',
    description: 'bp_analyzer_description',
    path: '/blood-pressure/',
    Icon: HeartPulse,
    gradient: 'from-red-500 to-orange-400',
  },
  {
    id: 'growth-charts',
    name: 'gcv_name',
    description: 'gcv_description_short',
    path: '/growth-charts/',
    Icon: LineChart,
    gradient: 'from-violet-500 to-purple-400',
  },
  {
    id: 'height-for-age',
    name: 'hfa_name',
    description: 'hfa_description_short',
    path: '/height-for-age/',
    Icon: PersonStanding,
    gradient: 'from-green-500 to-emerald-400',
  },
  {
    id: 'weight-for-age',
    name: 'wfa_name',
    description: 'wfa_description_short',
    path: '/weight-for-age/',
    Icon: Weight,
    gradient: 'from-yellow-500 to-amber-400',
  },
  {
    id: 'weight-for-length',
    name: 'wfl_name',
    description: 'wfl_description_short',
    path: '/weight-for-length/',
    Icon: Baby,
    gradient: 'from-sky-500 to-blue-400',
  },
  {
    id: 'weight-for-height',
    name: 'wfh_name',
    description: 'wfh_description_short',
    path: '/weight-for-height/',
    Icon: Scaling,
    gradient: 'from-lime-500 to-green-400',
  },
  {
    id: 'bmi-for-age',
    name: 'bfa_name',
    description: 'bfa_description_short',
    path: '/bmi-for-age/',
    Icon: Ruler,
    gradient: 'from-teal-500 to-cyan-400',
  },
  {
    id: 'head-circumference-for-age',
    name: 'hcfa_name',
    description: 'hcfa_description_short',
    path: '/head-circumference-for-age/',
    Icon: BrainCircuit,
    gradient: 'from-indigo-500 to-violet-400',
  },
  {
    id: 'arm-circumference-for-age',
    name: 'acfa_name',
    description: 'acfa_description_short',
    path: '/arm-circumference-for-age/',
    Icon: Armchair,
    gradient: 'from-rose-500 to-pink-400',
  },
  {
    id: 'triceps-skinfold-for-age',
    name: 'tsfa_name',
    description: 'tsfa_description_short',
    path: '/triceps-skinfold-for-age/',
    Icon: Bone,
    gradient: 'from-amber-500 to-yellow-400',
  },
  {
    id: 'subscapular-skinfold-for-age',
    name: 'ssfa_name',
    description: 'ssfa_description_short',
    path: '/subscapular-skinfold-for-age/',
    Icon: Bone,
    gradient: 'from-fuchsia-500 to-purple-400',
  },
   {
    id: 'history',
    name: 'history_name',
    description: 'history_description_short',
    path: '/history/',
    Icon: History,
    gradient: 'from-slate-500 to-gray-400',
  },
];
